Repository Lightning-AI/lightning_sphinx_theme, pull requests merged in 2022-08, with the labels that each got.

#41 Enable Side-by-Side Code Comparison and Improved Footnote Handling
  scss/_sphinx_base.scss
Labels: enhancement

#53 fix(ui) LAI2-10023: Remove black bar on the bottom of the docs pages
  pt_lightning_sphinx_theme/layout.html
  pt_lightning_sphinx_theme/static/css/theme.css
  pt_lightning_sphinx_theme/static/js/theme.js
  pt_lightning_sphinx_theme/static/js/vendor/anchor.min.js
  yarn.lock
Labels: bug

#54 Update Lightning Reference
  pt_lightning_sphinx_theme/layout.html
Labels: documentation
